client_id = "eca0a49cbec5b48483769d3419560d32"
name = "I95dev NetSuite Integration"
application_url = "https://i95dev-netsuite-integration.vercel.app"
embedded = true
handle = "i95dev-netsuite-integration-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [
  "https://i95dev-netsuite-integration.vercel.app/auth/callback",
  "https://i95dev-netsuite-integration.vercel.app/auth/shopify/callback",
  "https://i95dev-netsuite-integration.vercel.app/api/auth/callback"
]

[pos]
embedded = false
