# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eca0a49cbec5b48483769d3419560d32"
name = "I95dev NetSuite Integration"
application_url = "https://rendering-visible-movies-fields.trycloudflare.com"
embedded = true
handle = "i95dev-netsuite-integration-1"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rendering-visible-movies-fields.trycloudflare.com/auth/callback",
  "https://rendering-visible-movies-fields.trycloudflare.com/auth/shopify/callback",
  "https://rendering-visible-movies-fields.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[env]
